# Data Quality Check

## Import libraries

```{r}
library(xesreadR)
library(daqapo)
library(dplyr)
library(processmapR)
library(bupaR)
```

## Read XES

```{r}
event_log <- xesreadR::read_xes("./2_to_xes/mimicel.xes", validate = FALSE)
```

## Inspect `eventlog`

```{r}
event_log %>% base::summary()
```

```{r}
event_log %>% bupaR::mapping()
```

## Convert `eventlog` to `activitylog`

```{r}
event_log %>% bupaR::mutate(lifecycle_id = "complete") -> event_log
```

```{r}
event_log %>% bupaR::rename(start="timestamp") -> event_log
```

```{r}
event_log %>% 
  bupaR::activitylog(case_id = "CASE_concept_name", 
                     activity_id = "activity_id", 
                     resource_id = "resource_id",
                     timestamps = "start") -> activity_log
```

```{r}
activity_log %>% base::summary()
```

## Data Quality Assessment

### Detect activity frequency anomalies

```{r}
activity_log %>% daqapo::detect_activity_frequency_violations("Enter the ED" <= 1, "Triage in the ED" = 1)
```

### Detect 

### Detect Missing Values

```{r}
activity_log %>% daqapo::detect_missing_values(level_of_aggregation = "column", column = "CASE_gender")
```
